### ISSUE TITLE
line 145

### ISSUE THREAD

**Issue by Motophan** [Zetakov/sieve-rig#1]
tcl android phone says no file or directorty ./xmrig but compiles and I see the file with ls and it is a directory
xmrig inside that dir is dangling and points to nothing

but it does compile ??

**Comment by Zetakov** [comment]
Interesting. I haven't encountered this. I pushed a new version I have that was working for me a week ago. Also, check the directory `git/xmrig/build/` for the `xmrig` binary. 

It is suppose to soft link it to termux home dir. You can also:

```shell
cd ~
ln -s git/xmrig/build/xmrig xmrig
```

And see if that works. Then just run `./xmrig`. I'll be able to test this on a new phone in a week or so. Just waiting on some cables.

**Comment by Motophan** [comment]
sec. will update.

**Comment by Motophan** [comment]
before and after your sun link command. it is dangling. 

~/sieve-rig $ ls -alsh xmrig
0 lrwxrwxrwx 1 u0_a309 u0_a309 26 Feb  5 16:42 xmrig -> git/xmrig/build/xmrig
~/sieve-rig $

it appears to build successfully however

make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/data/data/com.termux/files/home/git/hwloc'
XMR Address: {redacted}
Worker Name: androidtlc
If all went as planned we will run xmrig-mo with benchmarking. If termux exits after benchmarking, either restart temux and xmrig or reboot the phone. This has to do with memory heaps being garbled during benchmarking.

Running xmrig and benchmarking....
./androidxmrig.sh: line 145: ./xmrig: No such file or directory

**Comment by Zetakov** [comment]
Ok. .Hold on. I'll test this out.

**Comment by Zetakov** [comment]
![xmrig](https://i.imgur.com/zJKGGW0l.jpg)

Okay it worked perfect for me. But here is what I had to do since I have previously ran this script on the phone. Basically a little clean-up

```shell
cd ~ && rm -rf xmrig git
git clone https://github.com/zetakov/sieve-rig
cd sieve-rig && cp androidxmrig.sh .. && cd ..
./androidxmrig.sh --mo
```

This is assuming you want the MoneroOcean xmrig.

**Comment by Motophan** [comment]
i didn't use the -mo flag
works great
